name: 'Source2Image'
description: 'Create image using source2image'
author: 'Vadim Rutkovsky'
icon: package
color: purple
inputs:
  path:
    description: 'Path to source code'
    default: '.'
    required: false
  base:
    description: 'source2image base image'
    required: true
  image:
    description: 'resulting image'
    required: true
  image_pull_username:
    description: "the username to use for pulling the base image"
    required: true
  image_pull_password:
    description: "the password to use for pulling the base image"
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.path }}
    - ${{ inputs.base }}
    - ${{ inputs.image }}
    - ${{ inputs.image_pull_username }}
    - ${{ inputs.image_pull_password }}